# Generated by Django 4.2.14 on 2024-07-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
